//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public byte id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Sehir { get; set; }
        public Nullable<short> Maas { get; set; }
        public string Durum { get; set; }
        public string yas { get; set; }
    }
}
